version: "3"

services:
  mygcc:
    build: ./
    volumes:
      - ../:/mnt
    tty: true
    working_dir: /mnt/10_01_make
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
